### ISSUE TITLE
! Package acro Error: Patching `longtable' failed. Please contact the acro author.

### ISSUE THREAD

**Issue by Sam1285** [cgnieder/acro#252]
! Package acro Error: Patching `longtable' failed. Please contact the acro author.

Can't say anything else. Was running smoth and now I get this error.

**Comment by TeXhackse** [comment]
longtable got an update and therefore the patch is no longer applying.
The patch is applied to add `\acswitchoff` while the longtable is not yet final. Without that one even more compilation runs might be necessary. You can disable it by using 

```
\acsetup{patch/longtable=false}
```

in your preamble. It's possible to locally replace the hook to work with the current version but I think it's easier to maintain when waiting for an update of acro.

**Comment by lorenzoFabbri** [comment]
I am also facing this issue:

> compilation failed- error
> Package acro Error: Patching `longtable' failed. Please contact the acro
> (acro)                author.

I am using Quarto with RStudio 2022.12.0 Build 353 (on KDE Plasma). My preamble looks like this:

```
---
format:
  pdf:
    documentclass: report
    pdf-engine: pdflatex
    include-in-header:
      - \usepackage{rotating}
      - \usepackage{float}
      - \usepackage{acro}
      - \acsetup{patch/longtable=false}
      - 
filters:
  - pandoc-acro

acronyms:
  edc:
    short: EDC
    long: endocrine distruptor
    short-plural: s
    long-plural: s
---
```
